version: '3'   
services:
    mongodb:
      image: mongo
      ports:
       - 8000:8001  
      environment:
       - mongo_db_admin_username=admin
       - mongo_db_admin_password=password
    mongoexpress:
      image: mongoexpress
      ports:
        - 8080:8080
      environment:
        - mongo_db_admin_username=admin  
